services:
  - type: web
    name: collabra-doc-backend
    runtime: python
    buildCommand: >
      pip install --upgrade pip &&
      pip install wheel &&
      pip install gunicorn &&
      PIP_NO_BUILD_ISOLATION=false pip install --upgrade --no-cache-dir -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT main:app
    autoDeploy: true
    envVars:
      - key: MONGODB_URL
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
